version: '3.8'

services:
  mcp-tg-jira-seminarapp:
    build:
      context: ./mcp-tg-jira-seminarapp
      dockerfile: Dockerfile
    container_name: mcp-tg-jira-seminarapp
    ports:
      - "8000:8000"
    environment:
      - JIRA_URL=${JIRA_URL}
      - JIRA_USER=${JIRA_USER}
      - JIRA_API_TOKEN=${JIRA_API_TOKEN}
    volumes:
      - ./mcp-tg-jira-seminarapp/src:/app/src
    restart: unless-stopped 