name: MCP GuruFocus - Comprehensive Testing

on:
  push:
    branches: [ master, main, develop ]
    paths:
      - 'mcp-gurufocus/**'
      - '.github/workflows/mcp-gurufocus-test.yml'
  pull_request:
    branches: [ master, main, develop ]
    paths:
      - 'mcp-gurufocus/**'
      - '.github/workflows/mcp-gurufocus-test.yml'
  workflow_dispatch:
    inputs:
      test_level:
        description: 'Test level to run'
        required: false
        default: 'standard'
        type: choice
        options:
        - standard
        - comprehensive
        - coverage-only

env:
  PYTHON_VERSION: '3.12'
  UV_VERSION: 'latest'
  WORKING_DIRECTORY: './mcp-gurufocus'

jobs:
  # Code Quality and Linting
  code-quality:
    runs-on: ubuntu-latest
    name: 🔍 Code Quality
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: ${{ env.UV_VERSION }}
          
      - name: Set up Python
        run: uv python install ${{ env.PYTHON_VERSION }}
        
      - name: Install dependencies
        run: uv sync
        working-directory: ${{ env.WORKING_DIRECTORY }}
        
      - name: Run ruff linting
        run: uv run ruff check .
        working-directory: ${{ env.WORKING_DIRECTORY }}
        
      - name: Run ruff formatting check
        run: uv run ruff format --check .
        working-directory: ${{ env.WORKING_DIRECTORY }}

  # Unit Tests
  unit-tests:
    runs-on: ubuntu-latest
    name: 🔬 Unit Tests
    needs: code-quality
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: ${{ env.UV_VERSION }}
          
      - name: Set up Python
        run: uv python install ${{ env.PYTHON_VERSION }}
        
      - name: Install dependencies
        run: uv sync --group test
        working-directory: ${{ env.WORKING_DIRECTORY }}
        
      - name: Run unit tests
        run: uv run --group test pytest tests/unit/ -v --tb=short
        working-directory: ${{ env.WORKING_DIRECTORY }}
        env:
          GURUFOCUS_API_KEY: ${{ secrets.TEST_API_KEY || 'test_api_key_123' }}

  # Integration Tests
  integration-tests:
    runs-on: ubuntu-latest
    name: 🔗 Integration Tests
    needs: unit-tests
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: ${{ env.UV_VERSION }}
          
      - name: Set up Python
        run: uv python install ${{ env.PYTHON_VERSION }}
        
      - name: Install dependencies
        run: uv sync --group test
        working-directory: ${{ env.WORKING_DIRECTORY }}
        
      - name: Run integration tests
        run: uv run --group test pytest tests/integration/ -v --tb=short
        working-directory: ${{ env.WORKING_DIRECTORY }}
        env:
          GURUFOCUS_API_KEY: ${{ secrets.TEST_API_KEY || 'test_api_key_123' }}
          
      - name: Run MCP tool unit tests
        run: uv run --group test pytest tests/unit/test_mcp_tools.py -v --tb=short
        working-directory: ${{ env.WORKING_DIRECTORY }}
        env:
          GURUFOCUS_API_KEY: ${{ secrets.TEST_API_KEY || 'test_api_key_123' }}

  # End-to-End Tests (Optional - may fail without real API)
  e2e-tests:
    runs-on: ubuntu-latest
    name: 🎯 End-to-End Tests
    needs: integration-tests
    continue-on-error: true  # Don't fail pipeline if E2E tests fail
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: ${{ env.UV_VERSION }}
          
      - name: Set up Python
        run: uv python install ${{ env.PYTHON_VERSION }}
        
      - name: Install dependencies
        run: uv sync --group test
        working-directory: ${{ env.WORKING_DIRECTORY }}
        
      - name: Run end-to-end tests
        run: uv run --group test pytest tests/e2e/ -v --tb=short -x
        working-directory: ${{ env.WORKING_DIRECTORY }}
        env:
          GURUFOCUS_API_KEY: ${{ secrets.TEST_API_KEY || 'test_api_key_123' }}
        continue-on-error: true

  # Coverage Analysis
  coverage:
    runs-on: ubuntu-latest
    name: 📊 Coverage Analysis
    needs: integration-tests
    if: github.event.inputs.test_level != 'coverage-only' || github.event_name != 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: ${{ env.UV_VERSION }}
          
      - name: Set up Python
        run: uv python install ${{ env.PYTHON_VERSION }}
        
      - name: Install dependencies
        run: uv sync --group test
        working-directory: ${{ env.WORKING_DIRECTORY }}
        
      - name: Run tests with coverage
        run: |
          uv run --group test pytest tests/unit/ tests/integration/ \
            --cov=app \
            --cov-report=term-missing \
            --cov-report=xml \
            --cov-report=html
        working-directory: ${{ env.WORKING_DIRECTORY }}
        env:
          GURUFOCUS_API_KEY: ${{ secrets.TEST_API_KEY || 'test_api_key_123' }}
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./mcp-gurufocus/coverage.xml
          flags: unittests
          name: mcp-gurufocus-codecov
          fail_ci_if_error: false
          
      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mcp-gurufocus-coverage-report
          path: |
            mcp-gurufocus/htmlcov/
            mcp-gurufocus/coverage.xml
          retention-days: 7

  # Comprehensive Testing (Docker-based)
  comprehensive-tests:
    runs-on: ubuntu-latest
    name: 🚀 Comprehensive Tests
    needs: code-quality
    if: github.event.inputs.test_level == 'comprehensive' || github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build test images
        run: docker-compose -f docker-compose.test.yml build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        
      - name: Run comprehensive test suite
        run: |
          chmod +x scripts/test-docker.sh
          ./scripts/test-docker.sh all
        working-directory: ${{ env.WORKING_DIRECTORY }}
        env:
          TEST_API_KEY: ${{ secrets.TEST_API_KEY || 'test_api_key_123' }}
          
      - name: Upload Docker test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mcp-gurufocus-docker-test-results
          path: |
            mcp-gurufocus/htmlcov/
            mcp-gurufocus/coverage.xml
          retention-days: 7

  # Security Scanning
  security-scan:
    runs-on: ubuntu-latest
    name: 🛡️ Security Scan
    needs: code-quality
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: ${{ env.UV_VERSION }}
          
      - name: Set up Python
        run: uv python install ${{ env.PYTHON_VERSION }}
        
      - name: Install dependencies
        run: uv sync
        working-directory: ${{ env.WORKING_DIRECTORY }}
        
      - name: Run safety scan
        run: |
          uv add --group dev "safety<3.0.0"
          uv run --group dev safety check
        working-directory: ${{ env.WORKING_DIRECTORY }}
        continue-on-error: true
        
      - name: Run bandit security scan
        run: |
          uv add --group dev bandit
          uv run --group dev bandit -r app/ -f json -o bandit-report.json
        working-directory: ${{ env.WORKING_DIRECTORY }}
        continue-on-error: true
        
      - name: Upload security artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mcp-gurufocus-security-reports
          path: |
            mcp-gurufocus/bandit-report.json
          retention-days: 7

  # Performance Tests (Optional)
  performance-tests:
    runs-on: ubuntu-latest
    name: ⚡ Performance Tests
    needs: integration-tests
    if: github.event.inputs.test_level == 'comprehensive'
    continue-on-error: true
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: ${{ env.UV_VERSION }}
          
      - name: Set up Python
        run: uv python install ${{ env.PYTHON_VERSION }}
        
      - name: Install dependencies
        run: |
          uv sync --group test
          uv add --group test pytest-benchmark
        working-directory: ${{ env.WORKING_DIRECTORY }}
          
      - name: Run performance benchmarks
        run: |
          uv run --group test pytest tests/unit/test_mcp_tools.py::TestMCPToolFunctions::test_concurrent_tool_execution \
            --benchmark-only --benchmark-json=benchmark.json
        working-directory: ${{ env.WORKING_DIRECTORY }}
        env:
          GURUFOCUS_API_KEY: ${{ secrets.TEST_API_KEY || 'test_api_key_123' }}
        continue-on-error: true
        
      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: mcp-gurufocus-performance-benchmarks
          path: mcp-gurufocus/benchmark.json
          retention-days: 7

  # Test Summary
  test-summary:
    runs-on: ubuntu-latest
    name: 📋 Test Summary
    needs: [unit-tests, integration-tests, coverage]
    if: always()
    
    steps:
      - name: Test Summary
        run: |
          echo "## MCP GuruFocus Test Results Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Test Type | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Code Quality | ${{ needs.code-quality.result == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Unit Tests | ${{ needs.unit-tests.result == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Integration Tests | ${{ needs.integration-tests.result == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Coverage Analysis | ${{ needs.coverage.result == 'success' && '✅ Passed' || '❌ Failed' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| E2E Tests | ${{ needs.e2e-tests.result == 'success' && '✅ Passed' || needs.e2e-tests.result == 'skipped' && '⏭️ Skipped' || '⚠️ Failed (Non-blocking)' }} |" >> $GITHUB_STEP_SUMMARY